# Use an official Node.js base image 
FROM node:18-alpine
# Set the working directory
WORKDIR /app
# Copy files 
COPY package*.json ./
COPY app.js .
COPY test.js .
# install dependencies
RUN npm install
# default command
CMD ["npm", "test"]